-- SQL Seed Script for Spymals Word Packs (including Spicy +18 Pack)
-- Run this in your Supabase SQL Editor if you ever need to reset or seed words directly in SQL.

INSERT INTO spymals_words (civilian, undercover, pack_name) VALUES
-- Pack Standard
('Café', 'Thé', 'standard'),
('Lait', 'Yaourt', 'standard'),
('Jus d''orange', 'Limonade', 'standard'),
('Coca-Cola', 'Pepsi', 'standard'),
('Bière', 'Cidre', 'standard'),
('Vin rouge', 'Vin blanc', 'standard'),
('Chocolat chaud', 'Cappuccino', 'standard'),
('Eau plate', 'Eau gazeuse', 'standard'),
('Smoothie', 'Milkshake', 'standard'),
('Thé glacé', 'Café frappé', 'standard'),
('Mojito', 'Caïpirinha', 'standard'),
('Tequila', 'Mezcal', 'standard'),
('Whisky', 'Bourbon', 'standard'),
('Vodka', 'Gin', 'standard'),
('Soleil', 'Lune', 'standard'),
('Étoile', 'Planète', 'standard'),
('Comète', 'Astéroïde', 'standard'),
('Galaxie', 'Nébuleuse', 'standard'),
('Satellite', 'Fusée', 'standard'),
('Guitare', 'Violon', 'standard'),
('Piano', 'Orgue', 'standard'),
('Batterie', 'Tambour', 'standard'),
('Flûte', 'Clarinette', 'standard'),
('Trompette', 'Saxophone', 'standard'),
('Football', 'Basketball', 'standard'),
('Tennis', 'Badminton', 'standard'),
('Rugby', 'Football américain', 'standard'),
('Natation', 'Plongée', 'standard'),
('Ski', 'Snowboard', 'standard'),
('Boxe', 'Karaté', 'standard'),

-- 🔥 Pack Soirée / +18 (spicy)
('Tequila Paf', 'Shot de Vodka', 'spicy'),
('Vodka Redbull', 'Jägerbomb', 'spicy'),
('Mojito', 'Sex on the Beach', 'spicy'),
('Beer Pong', 'Capitaine de Soirée', 'spicy'),
('Cuite', 'Gueule de bois', 'spicy'),
('Blackout', 'Trou de mémoire', 'spicy'),
('Open Bar', 'Happy Hour', 'spicy'),
('Shots', 'Pitcher de Bière', 'spicy'),
('Rentre en VTC', 'Dort sur le canapé', 'spicy'),
('Whisky-Coke', 'Rhum-Chararette', 'spicy'),
('Action ou Vérité', 'Jeu de la Bouteille', 'spicy'),
('Je n''ai jamais', 'Le Roi du Silence', 'spicy'),
('Strip-Poker', 'Action Coquine', 'spicy'),
('Striptease', 'Lap Dance', 'spicy'),
('Twerk', 'Slow', 'spicy'),
('Glace à sucer', 'Sucette', 'spicy'),
('Bisou volé', 'Pelle', 'spicy'),
('Coup d''un soir', 'Friends with benefits', 'spicy'),
('Sex-appeal', 'Charme naturel', 'spicy'),
('Plan Q', 'Relation libre', 'spicy'),
('Préservatif', 'Lubrifiant', 'spicy'),
('Menottes', 'Bandeau sur les yeux', 'spicy'),
('Fouet', 'Plume', 'spicy'),
('Nuisette', 'Lingerie', 'spicy'),
('String', 'Tanga', 'spicy'),
('Dentelle', 'Cuir', 'spicy'),
('Sex-toy', 'Vibreur', 'spicy'),
('Menottes en moumoute', 'Attaches de lit', 'spicy'),
('Jeu de rôle', 'Fantasme', 'spicy'),
('Caresse', 'Chatouille', 'spicy'),
('Massage érotique', 'Massage suédois', 'spicy'),
('Huile de massage', 'Gel chauffant', 'spicy'),
('Bain à bulles', 'Jacuzzi', 'spicy'),
('Preservatif goût fraise', 'Preservatif nervuré', 'spicy'),
('Sexto', 'Nude', 'spicy'),
('Caméra cachée', 'Miroir au plafond', 'spicy'),
('Missionnaire', 'Lévrette', 'spicy'),
('69', 'Cuillère', 'spicy'),
('Andalouse', 'Amazonienne', 'spicy'),
('Orgasme', 'Frisson', 'spicy'),
('Désir', 'Tentation', 'spicy'),
('Péché', 'Interdit', 'spicy'),
('Chambre d''hôtel', 'Love Room', 'spicy');
